#!/usr/bin/env python3
"""Enable and monitor an ESP32 module running a standalone onboard policy.

Example:
    python examples/onboard_policy_monitor.py --module-ids 11
"""

from __future__ import annotations

import argparse
import json
import signal
import sys
import time
from pathlib import Path

import numpy as np

PROJECT_ROOT = Path(__file__).parent.parent.resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

DEFAULT_POLICY_MANIFEST = (
    PROJECT_ROOT / "capy_esp32" / "data" / "policy_manifest.json"
)


def _signal_handler(signum, frame):
    del signum, frame
    sys.stdout.write("\033[?25h")
    sys.stdout.write("\033[0m")
    sys.stdout.flush()
    print("\n[Onboard] Shutting down...")
    sys.exit(0)


def _load_cfg(config_ref: str):
    from metamachine.environments.configs.config_registry import ConfigRegistry

    config_path = Path(config_ref)
    if config_path.exists():
        return ConfigRegistry.create_from_file(str(config_path))
    return ConfigRegistry.create_from_name(config_ref)


def _load_policy_hash(manifest_path: Path, override: int | None) -> int:
    if override is not None:
        return int(override)
    if not manifest_path.exists():
        raise FileNotFoundError(
            f"Policy manifest not found: {manifest_path}. "
            "Pass --policy-hash or regenerate with convert_policy_pkl_to_bin.py."
        )
    data = json.loads(manifest_path.read_text())
    policy_hash = int(data.get("policy_hash", 0))
    if policy_hash <= 0:
        raise ValueError(f"Invalid policy hash in {manifest_path}: {policy_hash}")
    print(f"[Onboard] Policy hash: {policy_hash} ({data.get('policy_hash_hex', 'n/a')})")
    return policy_hash


def _build_real_env(cfg, module_ids):
    from omegaconf import OmegaConf
    from metamachine.environments.env_real import RealMetaMachine

    if module_ids is not None:
        if "real" not in cfg or cfg.real is None:
            cfg.real = OmegaConf.create({})
        cfg.real.module_ids = list(module_ids)

    cfg.environment.mode = "real"
    return RealMetaMachine(cfg)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=str,
        default="real_one_module",
        help="Config name or YAML path for RealMetaMachine",
    )
    parser.add_argument(
        "--module-ids",
        type=int,
        nargs="+",
        default=None,
        metavar="ID",
        help="Override active module IDs from config",
    )
    parser.add_argument(
        "--policy-manifest",
        type=Path,
        default=DEFAULT_POLICY_MANIFEST,
        help="Path to policy_manifest.json generated by convert_policy_pkl_to_bin.py",
    )
    parser.add_argument(
        "--policy-hash",
        type=int,
        default=None,
        help="Override policy hash instead of reading policy_manifest.json",
    )
    parser.add_argument(
        "--control-dt",
        type=float,
        default=None,
        help="PC-side send interval in seconds (default: cfg.control.dt)",
    )
    parser.add_argument(
        "--disable-filter",
        action="store_true",
        help="Disable the ESP32-side low-pass filter in outgoing commands",
    )
    parser.add_argument(
        "--policy-debug-print-hz",
        type=float,
        default=1.0,
        help="Console print rate for per-module policy feedback",
    )
    parser.add_argument(
        "--auto-enable",
        action="store_true",
        help="Enable motors automatically once all modules are connected",
    )
    args = parser.parse_args()

    from hierarchical.scripts.real_master_runtime import (
        PolicyFeedbackMonitor,
        send_keepalive,
        send_per_module_command_context,
        wait_until_policy_ready,
    )

    signal.signal(signal.SIGINT, _signal_handler)

    cfg = _load_cfg(args.config)
    if args.disable_filter:
        if "real" not in cfg or cfg.real is None:
            cfg.real = {}
        cfg.real.enable_filter = False

    real_env = _build_real_env(cfg, args.module_ids)
    policy_hash = _load_policy_hash(args.policy_manifest.resolve(), args.policy_hash)
    control_dt = float(args.control_dt or cfg.control.dt)

    callbacks = []
    if args.policy_debug_print_hz > 0:
        monitor = PolicyFeedbackMonitor(
            real_env.expected_module_ids,
            args.policy_debug_print_hz,
        )
        callbacks.append(monitor.update)

    if callbacks:
        def _feedback(module_id: int, msg, received_at: float) -> None:
            for callback in callbacks:
                callback(module_id, msg, received_at)
        real_env.policy_feedback_callback = _feedback

    num_modules = len(real_env.expected_module_ids)
    zero_command_context = np.zeros((num_modules, 0), dtype=np.float32)

    print("=" * 60)
    print("Standalone Onboard Policy Monitor")
    print("=" * 60)
    print(f"  Config:        {args.config}")
    print(f"  Module IDs:    {real_env.expected_module_ids}")
    print(f"  Control dt:    {control_dt:.3f}s ({1.0 / control_dt:.1f} Hz)")
    print(f"  Policy hash:   {policy_hash}")
    print(f"  Manifest:      {args.policy_manifest.resolve()}")
    print()
    print("[Onboard] Keyboard:")
    print("  e enable motors | d disable | c calibrate | r restart | v sim2real check")
    print("  Ctrl+C exits")
    print()

    try:
        print("[Onboard] Waiting for all modules to connect...")
        while not real_env.all_modules_connected():
            real_env.receive_module_data()
            real_env._check_input()
            send_keepalive(real_env, policy_hash)
            real_env._update_dashboard_performance()
            print(
                f"  Waiting for modules: {real_env.get_missing_modules()}",
                end="\r",
            )
            time.sleep(0.1)

        print("\n[Onboard] All modules connected.")
        if args.auto_enable and not real_env.motor_enabled:
            real_env._enable_motor()

        if not wait_until_policy_ready(real_env, policy_hash):
            return

        print("[Onboard] Runtime ready. Sending onboard-policy keepalive commands.")
        t_next = time.perf_counter()

        while True:
            real_env._get_observable_data()
            real_env._check_input()

            if not real_env.ready():
                if not wait_until_policy_ready(real_env, policy_hash, allow_disconnect=True):
                    t_next = time.perf_counter()
                    continue
                t_next = time.perf_counter()
                continue

            send_per_module_command_context(
                real_env,
                zero_command_context,
                real_env.state,
                policy_hash,
            )
            real_env._update_dashboard_performance()

            t_next += control_dt
            sleep_time = t_next - time.perf_counter()
            if sleep_time > 0:
                time.sleep(sleep_time)
            else:
                t_next = time.perf_counter()
    except KeyboardInterrupt:
        print("\n[Onboard] Stopped by user.")
    finally:
        real_env.policy_feedback_callback = None
        real_env.close()


if __name__ == "__main__":
    main()
